/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Legend": "传说",
    "NEW": "新",
    "Rarity": "稀有度",
    "Rare": "稀有",
    "Reset": "重置",
    "Sale Price:": "出售价格:",
    "Save to Clipboard": "保存到剪贴板",
    "Save & Load": "保存 & 加载",
    "Skills": "技能",
    "Stone": "石头",
    "Swipe cards to flip them over": "鼠标悬浮卡片以翻转",
    "Base": "基础",
    "Basic": "基础",
    "Battles": "战斗",
    "Buy:": "购买:",
    "Black Hole Pokes:": "点击黑洞:",
    "Can you collect them all?": "你能集齐它们吗？",
    "Cancel": "取消",
    "Card Collection": "卡片收集",
    "Cards": "卡片",
    "Card Size:": "卡片尺寸:",
    "Stats": "统计",
    "Rocks": "岩石",
    "The moment you entered, my sleeves shimmered harder.": "你一进来，我的袖子就更亮了。",
    "Tooth": "牙齿",
    "Total Owned": "总计拥有",
    "Unlocked": "已解锁",
    "Undiscovered Cards": "未发现的卡片",
    "Unpurchased": "未购买",
    "Value": "价值",
    "Welcome to Cosmic Collection - an Incremental Collectible Card Game!": "欢迎来到宇宙收集-一个增量收集卡牌游戏！",
    "Your standard traveling merchant": "你的标准旅行商人",
    "Zeal": "热情",
    "This can only be used once per day!": "这个一天只能用一次！",
    "Owned": "已拥有",
    "Pollen": "花粉",
    "Preferences": "首选项",
    "Probability": "概率",
    "Pearl": "珍珠",
    "Please Rotate Your Device": "请旋转你的设备",
    "Poke Cooldown": "卡片冷却时间",
    "Poke the black hole and see what it spits out": "点一下黑洞，看看它会吐出什么",
    "Are you sure you want to reset your game? This will delete all your progress and cannot be undone.": "你确定要重置游戏吗？这将删除您的所有进度，并且无法撤消。",
    "Auto-Use Max Absorber": "自动使用最大吸收器",
    "Chance": "几率",
    "Coin": "硬币",
    "Confirm": "确认",
    "Load from Clipboard": "从剪贴板载入",
    "Load from File": "从文件载入",
    "Max Offline Time": "最大离线时间",
    "Max Cards per Poke": "每次点击可获得的最大卡片数量",
    "Merchant": "商人",
    "Merchants": "商人",
    "Merchant # Cards": "商人 # 卡片",
    "Merchant Cooldown Reduction": "商人冷却时间减少",
    "Merchant Price Divider": "商业价格除法器",
    "Merchant Purchases:": "商人购买:",
    "Hole": "黑洞",
    "Got it!": "知道了!",
    "Name:": "名称:",
    "Mythic": "神话",
    "Mult": "乘数",
    "Junk": "垃圾",
    "Odds": "几率",
    "Realm": "领域",
    "Rune": "符文",
    "Royal Jelly": "蜂王浆",
    "Reset Game": "重置游戏",
    "Remove any active cooldown": "移除任何有效的冷却时间",
    "Spirit": "精神",
    "Show Tier Ups in Collection": "在收集中显示分级",
    "The longer you wait, the shinier they get. Or maybe that’s just you.": "你等得越久，它们就越亮。也许只有你这样。",
    "This feature is intended only for when you accidentally used realm filters with an astronomically high cooldown. This will:": "此功能仅适用于当您意外使用具有天文数字高冷却时间的领域过滤器时。这将:",
    "This game is best played in landscape mode": "这个游戏最好在横屏模式下玩",
    "Tier Progress (Experimental/Spoilers)": "层级进度（实验性/剧透）",
    "What’s this glow? Oh, right—it’s just your collection’s reputation.": "这是什么光？对了，这只是你收藏的名声。",
    "Coral": "珊瑚",
    "Cooldown Skip Chance": "冷却跳过几率",
    "Cooldown Divider": "冷却除法器",
    "Click cards to see details": "点击卡片查看详细信息",
    "Cards Offered:": "提供卡牌数量：",
    "Ah! If appearances were rarities, you’d be beyond exotic.": "啊!如果外表是稀有的，那你就太独特了。",
    "Currency": "货币",
    "Currencies": "货币",
    "Cosmic Ray": "宇宙射线",
    "Crystal": "水晶",
    "Egg": "鸡蛋",
    "Epic": "史诗",
    "Exotic": "独特",
    "Explore the tabs on top to see your collection, skills, and more": "探索顶部的选项卡，以查看您的收集、技能等",
    "Feather": "羽毛",
    "Extra Merchant Rarity Scaling": "额外的商人稀有度比例",
    "Fine": "不错",
    "From Generators": "从生成器",
    "From Cards": "从卡片",
    "Gen Mult": "批量生成",
    "Min Cards per Poke": "每次点击获得的最小卡片数",
    "Offer Duration:": "优惠期限：",
    "Save to File": "另存为文件",
    "Rarity Scaling:": "稀有度比例:",
    "This offer was banned in 12 kingdoms for being too generous.": "这一提议因过于慷慨而被12个王国禁止。",
    "Gain / Second": "增益 / 秒",
    "Gain / Poke": "增益 / 点击",
    "Global Effects": "全局效果",
    "Global Gains": "全局增益",
    "How about all of them for 5% off?": "全部打九五折怎么样？",
    "I'm sure you can figure the rest out. Enjoy!": "我相信你能解决剩下的问题。好好享受吧！",
    "Keep all your other progress": "保持其他所有的进度",
    "Ahoy there! Has anyone ever told you your presence is rarer than a mythic foil?": "喂! !有没有人告诉过你，你的存在比神话中的陪衬还要罕见？",
    "Danger Zone": "危险区域",
    "Black Hole pokes and Merchants can now give cards from Sea World realm.": "黑洞点击和商人现在可以提供来自海洋世界领域的卡片了。",
    "Dark Theme": "深色主题",
    "Decrease base cooldown for Rocks by 0.5s.": "减少岩石的基础冷却时间0.5s。",
    "Decent": "体面",
    "Discovered": "已发现",
    "Description:": "介绍:",
    "General Stats": "常规统计",
    "Faster Merchant": "更快的商人",
    "Faster Poke": "更快的点击",
    "Divine": "神圣",
    "Fan of Capitalism": "资本主义的粉丝",
    "Get Unstuck": "摆脱困境",
    "Lucky Skip": "幸运跳跃",
    "Massive Black Hole": "巨大的黑洞",
    "More Cards": "更多卡片",
    "Not Less Cards": "不减少卡片",
    "Probability:": "概率:",
    "Reduce merchant refresh time by 5 seconds.": "减少商人刷新时间5秒。",
    "This pile right here? It's why they invented binders with zippers.": "这一堆？所以才发明了带拉链的活页夹。",
    "Unlock Sea World Realm": "解锁海洋世界领域",
    "Rarity:": "稀有度:",
    "Realm:": "领域:",
    "Today’s deal? Straight from the top shelf of destiny.": "今天的交易？直接从命运的顶层架子上取下来。",
    "Effects": "效果",
    "Hark! Is that the scent of foil and confidence I detect?": "听!这是我闻到的箔纸和自信的味道吗？",
    "JUNK": "垃圾",
    "Limestone": "石灰岩",
    "Limestone makes up most coral reefs and contains the skeletons of ancient sea life.": "石灰岩构成了大多数珊瑚礁，并包含了古代海洋生物的骨架。",
    "Even my lucky coin saluted you.": "连我的幸运硬币都向你致敬。",
    "Progress": "进度",
    "No mystery packs here—just stacks of shimmering certainty.": "这里没有神秘的礼包，只有一堆堆闪闪发光的确定性。",
    "Resources": "资源",
    "A little bit of luck. A whole lot of win.": "一点点运气。一大堆的胜利。",
    "Light Theme": "浅色主题",
    "Step aside, holographics—true brilliance is here.": "靠边站，全息摄影——真正的辉煌在这里。",
    "Ancient Relics": "古代遗物",
    "Aviary": "鸟舍",
    "+Cards": "+卡片",
    "Bugdom": "昆虫王国",
    "Celestial Bodies": "天体",
    "Cooldown": "冷却时间",
    "Greek Gods": "希腊诸神",
    "Greetings, enchantment incarnate! Have you been bathing in mythic energy again?": "你好，魔法的化身！你又沐浴在神话能量中了吗？",
    "Incremental Games": "增量游戏",
    "Mythical Beasts": "神兽",
    "Per Poke": "每次点击",
    "Per Sec": "每秒",
    "Rarities": "稀有物",
    "Realms": "领域",
    "Sea World": "海洋世界",
    "Spirit Familiars": "灵宠",
    "These deals are layered like a well-structured deck. And twice as dangerous.": "这些交易是分层的，就像一个结构良好的桥牌。而且危险加倍。",
    "Weapons": "武器",
    "/ Poke:": "/ 点击:",
    "Rare Income": "稀有收入",
    "Iron Ore": "铁矿石",
    "Level Up": "升级",
    "Locked": "未解锁",
    "Purchased": "已购买",
    "Sandstone": "砂岩",
    "BASIC": "基础",
    "Affordable": "经济实惠",
    "Anomaly": "异常",
    "Binder envy begins right here.": "对活页夹的羡慕就从这里开始。",
    "Card Supernova": "卡片超新星",
    "Casual Gamer": "休闲玩家",
    "Cooldown Divider:": "冷却时间分配:",
    "Every bundle here was curated for the chosen—aka, you.": "这里的每一捆都是为被选中的人精心策划的，也就是你。",
    "Flint": "燧石",
    "Flint was used for tools and fire-starting by early humans over 2 million years ago.": "燧石在200多万年前被早期人类用来制作工具和生火。",
    "Go Away Aldric!": "走开，奥尔德里奇！",
    "Iron ore mining dates back more than 4000 years to ancient Egypt.": "铁矿开采可以追溯到4000多年前的古埃及。",
    "Max Cards per Poke:": "每戳最大卡数：",
    "Merchant Pack Up and Leave Faster": "商人打包离开速度加快",
    "No More Junk": "不再有垃圾",
    "No skills match the current filters.": "没有符合当前筛选条件的技能",
    "Nobody Likes Rocks": "没人喜欢石头",
    "odds divider:": "几率除法器:",
    "Sandstone can form stunning canyons like Antelope Canyon in Arizona.": "砂岩可以形成令人惊叹的峡谷，比如亚利桑那州的羚羊峡谷。",
    "Shorter Sacrifice": "更短的牺牲",
    "Some stone fragments contain tiny fossils that are millions of years old!": "一些石头碎片含有数百万年前的微小化石！",
    "Special Effects": "特殊效果",
    "Stone Fragment": "石头碎片",
    "The room just leveled up. That’s your passive aura, isn’t it?": "这房间刚刚升级。那是你的被动光环，不是吗？",
    "They said divine cards don’t exist. Then you arrived.": "他们说神牌不存在。然后你来了。",
    "We Will Not Rock You": "我们不会震撼你",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Aldric Farwander": "Aldric Farwander",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Reset all currencies to ": "将所有货币重置为 ",
    "Lvl: ": "等级: ",
    "Tier: ": "层级: ",
    "Qty: ": "数量: ",
    "Time Offline: ": "离线时间: ",
    "(Unlocks at level ": "(解锁于等级 ",
    "Max Lvl ": "最大等级 ",
    "Unlock New Merchant ": "解锁新商人 ",
    "Absorber Upgrade ": "吸收器升级 ",
    "Resource Generator ": "资源生成器 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "% chance to skip Black Hole cooldown.": "% 几率以跳过黑洞冷却时间.",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^T([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^\(base: (.+) lvl × (.+) tier\)$/, '(基础: $1 等级 × $2 层级)'],
    [/^\((.+) base: (.+) lvl × (.+) tier\)$/, '($1 基础: $2 等级 × $3 层级)'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^\+([\d\.,]+) to max cards per poke.$/, '\+$1 每次点击获得的卡片上限。'],
    [/^\+([\d\.,]+) to min cards per poke.$/, '\+$1 每次点击获得的卡片下限。'],
    [/^\+([\d\.,]+) card offered by merchants.$/, '\+$1 商人提供的卡片。'],
    [/^Rare Income ([\d\.,]+)$/, '稀有收入 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Next Tier at Qty ([\d\.,]+)$/, '到下一层级需要数量 $1'],
    [/^Leaves in ([\d\.,]+)s$/, '$1秒后离开'],
    [/^Leaves in ([\d\.,]+)m([\d\.,]+)s$/, '$1分$2秒后离开'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) for Tier ([\d\.,]+)$/, '$1 到层级 $2'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);