/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Legend": "传说",
    "NEW": "新",
    "Rarity": "稀有度",
    "Rare": "稀有",
    "Reset": "重置",
    "Sale Price:": "出售价格:",
    "Save to Clipboard": "保存到剪贴板",
    "Save & Load": "保存 & 加载",
    "Skills": "技能",
    "Stone": "石头",
    "Swipe cards to flip them over": "鼠标悬浮卡片以翻转",
    "Base": "基础",
    "Basic": "基础",
    "Battles": "战斗",
    "Buy:": "购买:",
    "Black Hole Pokes:": "点击黑洞:",
    "Can you collect them all?": "你能集齐它们吗？",
    "Cancel": "取消",
    "Card Collection": "卡片收集",
    "Cards": "卡片",
    "Card Size:": "卡片尺寸:",
    "Stats": "统计",
    "Rocks": "岩石",
    "The moment you entered, my sleeves shimmered harder.": "你一进来，我的袖子就更亮了。",
    "Tooth": "牙齿",
    "Total Owned": "总计拥有",
    "Unlocked": "已解锁",
    "Undiscovered Cards": "未发现的卡片",
    "Unpurchased": "未购买",
    "Value": "价值",
    "Welcome to Cosmic Collection - an Incremental Collectible Card Game!": "欢迎来到宇宙收集-一个增量收集卡牌游戏！",
    "Your standard traveling merchant": "你的标准旅行商人",
    "Zeal": "热情",
    "This can only be used once per day!": "这个一天只能用一次！",
    "Owned": "已拥有",
    "Pollen": "花粉",
    "Preferences": "首选项",
    "Probability": "概率",
    "Pearl": "珍珠",
    "Please Rotate Your Device": "请旋转你的设备",
    "Poke Cooldown": "卡片冷却时间",
    "Poke the black hole and see what it spits out": "点一下黑洞，看看它会吐出什么",
    "Are you sure you want to reset your game? This will delete all your progress and cannot be undone.": "你确定要重置游戏吗？这将删除您的所有进度，并且无法撤消。",
    "Auto-Use Max Absorber": "自动使用最大吸收器",
    "Chance": "几率",
    "Coin": "硬币",
    "Confirm": "确认",
    "Load from Clipboard": "从剪贴板载入",
    "Load from File": "从文件载入",
    "Max Offline Time": "最大离线时间",
    "Max Cards per Poke": "每次点击可获得的最大卡片数量",
    "Merchant": "商人",
    "Merchants": "商人",
    "Merchant # Cards": "商人 # 卡片",
    "Merchant Cooldown Reduction": "商人冷却时间减少",
    "Merchant Price Divider": "商业价格除法器",
    "Merchant Purchases:": "商人购买:",
    "Hole": "黑洞",
    "Got it!": "知道了!",
    "Name:": "名称:",
    "Mythic": "神话",
    "Mult": "乘数",
    "Junk": "垃圾",
    "Odds": "几率",
    "Realm": "领域",
    "Rune": "符文",
    "Royal Jelly": "蜂王浆",
    "Reset Game": "重置游戏",
    "Remove any active cooldown": "移除任何有效的冷却时间",
    "Spirit": "精神",
    "Show Tier Ups in Collection": "在收集中显示分级",
    "The longer you wait, the shinier they get. Or maybe that’s just you.": "你等得越久，它们就越亮。也许只有你这样。",
    "This feature is intended only for when you accidentally used realm filters with an astronomically high cooldown. This will:": "此功能仅适用于当您意外使用具有天文数字高冷却时间的领域过滤器时。这将:",
    "This game is best played in landscape mode": "这个游戏最好在横屏模式下玩",
    "Tier Progress (Experimental/Spoilers)": "层级进度（实验性/剧透）",
    "What’s this glow? Oh, right—it’s just your collection’s reputation.": "这是什么光？对了，这只是你收藏的名声。",
    "Coral": "珊瑚",
    "Cooldown Skip Chance": "冷却跳过几率",
    "Cooldown Divider": "冷却除法器",
    "Click cards to see details": "点击卡片查看详细信息",
    "Cards Offered:": "提供卡片数量：",
    "Ah! If appearances were rarities, you’d be beyond exotic.": "啊!如果外表是稀有的，那你就太独特了。",
    "Currency": "货币",
    "Currencies": "货币",
    "Cosmic Ray": "宇宙射线",
    "Crystal": "水晶",
    "Egg": "鸡蛋",
    "Epic": "史诗",
    "Exotic": "独特",
    "Explore the tabs on top to see your collection, skills, and more": "探索顶部的选项卡，以查看您的收集、技能等",
    "Feather": "羽毛",
    "Extra Merchant Rarity Scaling": "额外的商人稀有度比例",
    "Fine": "优秀",
    "From Generators": "从生成器",
    "From Cards": "从卡片",
    "Gen Mult": "批量生成",
    "Min Cards per Poke": "每次点击获得的最小卡片数",
    "Offer Duration:": "优惠期限：",
    "Save to File": "另存为文件",
    "Rarity Scaling:": "稀有度比例:",
    "This offer was banned in 12 kingdoms for being too generous.": "这一提议因过于慷慨而被12个王国禁止。",
    "Gain / Second": "增益 / 秒",
    "Gain / Poke": "增益 / 点击",
    "Global Effects": "全局效果",
    "Global Gains": "全局增益",
    "How about all of them for 5% off?": "全部打九五折怎么样？",
    "I'm sure you can figure the rest out. Enjoy!": "我相信你能解决剩下的问题。好好享受吧！",
    "Keep all your other progress": "保持其他所有的进度",
    "Ahoy there! Has anyone ever told you your presence is rarer than a mythic foil?": "喂! !有没有人告诉过你，你的存在比神话中的陪衬还要罕见？",
    "Danger Zone": "危险区域",
    "Black Hole pokes and Merchants can now give cards from Sea World realm.": "黑洞点击和商人现在可以提供来自海洋世界领域的卡片了。",
    "Dark Theme": "深色主题",
    "Decrease base cooldown for Rocks by 0.5s.": "减少岩石的基础冷却时间0.5s。",
    "Decent": "良好",
    "Discovered": "已发现",
    "Description:": "介绍:",
    "General Stats": "常规统计",
    "Faster Merchant": "更快的商人",
    "Faster Poke": "更快的点击",
    "Divine": "神圣",
    "Fan of Capitalism": "资本主义的粉丝",
    "Get Unstuck": "摆脱困境",
    "Lucky Skip": "幸运跳跃",
    "Massive Black Hole": "巨大的黑洞",
    "More Cards": "更多卡片",
    "Not Less Cards": "不减少卡片",
    "Probability:": "概率:",
    "Reduce merchant refresh time by 5 seconds.": "减少商人刷新时间5秒。",
    "This pile right here? It's why they invented binders with zippers.": "这一堆？所以才发明了带拉链的活页夹。",
    "Unlock Sea World Realm": "解锁海洋世界领域",
    "Rarity:": "稀有度:",
    "Realm:": "领域:",
    "Today’s deal? Straight from the top shelf of destiny.": "今天的交易？直接从命运的顶层架子上取下来。",
    "Effects": "效果",
    "Hark! Is that the scent of foil and confidence I detect?": "听!这是我闻到的箔纸和自信的味道吗？",
    "JUNK": "垃圾",
    "Limestone": "石灰岩",
    "Limestone makes up most coral reefs and contains the skeletons of ancient sea life.": "石灰岩构成了大多数珊瑚礁，并包含了古代海洋生物的骨架。",
    "Even my lucky coin saluted you.": "连我的幸运硬币都向你致敬。",
    "Progress": "进度",
    "No mystery packs here—just stacks of shimmering certainty.": "这里没有神秘的礼包，只有一堆堆闪闪发光的确定性。",
    "Resources": "资源",
    "A little bit of luck. A whole lot of win.": "一点点运气。一大堆的胜利。",
    "Light Theme": "浅色主题",
    "Step aside, holographics—true brilliance is here.": "靠边站，全息摄影——真正的辉煌在这里。",
    "Ancient Relics": "古代遗物",
    "Aviary": "鸟舍",
    "+Cards": "+卡片",
    "Bugdom": "昆虫王国",
    "Celestial Bodies": "天体",
    "Cooldown": "冷却时间",
    "Greek Gods": "希腊诸神",
    "Greetings, enchantment incarnate! Have you been bathing in mythic energy again?": "你好，魔法的化身！你又沐浴在神话能量中了吗？",
    "Incremental Games": "增量游戏",
    "Mythical Beasts": "神兽",
    "Per Poke": "每次点击",
    "Per Sec": "每秒",
    "Rarities": "稀有物",
    "Realms": "领域",
    "Sea World": "海洋世界",
    "Spirit Familiars": "灵宠",
    "These deals are layered like a well-structured deck. And twice as dangerous.": "这些交易是分层的，就像一个结构良好的桥卡片。而且危险加倍。",
    "Weapons": "武器",
    "/ Poke:": "/ 点击:",
    "Rare Income": "稀有收入",
    "Iron Ore": "铁矿石",
    "Level Up": "升级",
    "Locked": "未解锁",
    "Purchased": "已购买",
    "Sandstone": "砂岩",
    "BASIC": "基础",
    "Affordable": "经济实惠",
    "Binder envy begins right here.": "对活页夹的羡慕就从这里开始。",
    "Cooldown Divider:": "冷却时间分配:",
    "Every bundle here was curated for the chosen—aka, you.": "这里的每一捆都是为被选中的人精心策划的，也就是你。",
    "Flint": "燧石",
    "Flint was used for tools and fire-starting by early humans over 2 million years ago.": "燧石在200多万年前被早期人类用来制作工具和生火。",
    "Go Away Aldric!": "走开，奥尔德里奇！",
    "Iron ore mining dates back more than 4000 years to ancient Egypt.": "铁矿开采可以追溯到4000多年前的古埃及。",
    "Max Cards per Poke:": "每点击最大卡数：",
    "Merchant Pack Up and Leave Faster": "商人打包离开速度加快",
    "No More Junk": "不再有垃圾",
    "No skills match the current filters.": "没有符合当前筛选条件的技能",
    "Nobody Likes Rocks": "没人喜欢石头",
    "odds divider:": "几率除法器:",
    "Sandstone can form stunning canyons like Antelope Canyon in Arizona.": "砂岩可以形成令人惊叹的峡谷，比如亚利桑那州的羚羊峡谷。",
    "Some stone fragments contain tiny fossils that are millions of years old!": "一些石头碎片含有数百万年前的微小化石！",
    "Special Effects": "特殊效果",
    "Stone Fragment": "石头碎片",
    "The room just leveled up. That’s your passive aura, isn’t it?": "这房间刚刚升级。那是你的被动光环，不是吗？",
    "They said divine cards don’t exist. Then you arrived.": "他们说神卡片不存在。然后你来了。",
    "We Will Not Rock You": "我们不会震撼你",
    "/ Sec:": "/ 秒:",
    "A strong dude. Carries twice as many cards.": "一个强壮的家伙。携带两倍的卡片。",
    "Always on the move. She only stays for half as long.": "总是在移动。她只待了一半的时间。",
    "By my sleeves! It's the glamour and the glory in one!": "抓住我的袖子！它集魅力与荣耀于一身！",
    "Think fast. Click faster.": "思考快速。点击更快。",
    "You must unlock Greek Gods realm to access Battles": "需要解锁希腊诸神领域才能进入战斗",
    "Pebble": "卵石",
    "Pebbles can form protective barriers called pebble beaches that shield shorelines from strong waves.": "鹅卵石可以形成被称为卵石滩的保护性屏障，保护海岸线免受大浪的侵袭。",
    "TIER UP": "层级可提升",
    "Here’s the deal: a little bit of junk, a whole lot of wow.": "事情是这样的：一点点垃圾，一大堆哇。",
    "Coal": "煤",
    "A fine day to greet the collector of gods.": "这是迎接众神收集者的好天气。",
    "A legendary walk, an exotic stare, a divine vibe.": "传说中的漫步，异域的眼神，神圣的气息。",
    "Coal is formed from ancient plants that lived over 300 million years ago!": "煤是由生活在3亿多年前的古老植物形成的！",
    "Copper Nugget": "铜块",
    "Shale": "页岩",
    "Every card here has been blessed with good vibes.": "里的每张卡片都被赋予了良好的氛围。",
    "Look at that one! And that one! And—okay, you get it. They're all amazing.": "看那个！还有那个！好吧，你懂的。他们都很棒。",
    "Shale layers can trap natural gas and oil, shaping modern fracking.": "页岩层可以捕获天然气和石油，塑造了现代水力压裂法。",
    "↑ req": "↑ 需要",
    "↓ owned": "↓ 拥有",
    "Hey there, binder boss! That outfit? Full-art worthy.": "嗨，活页夹老板！那套衣服？完全有艺术价值。",
    "Are you charisma-capped? Because you’re off the charts.": "你的魅力有上限吗？因为你太棒了。",
    "These bundles have critical hit rates built in.": "这些捆绑包内置了暴击率。",
    "Copper was the first metal ever used by humans, over 10,000 years ago.": "一万多年前，铜是人类使用的第一种金属。",
    "Top of the day! Your hair flows like a stack of well-organized fine cards.": "今天真是太棒了！你的头发像一叠精心整理的精美卡片。",
    "Value so potent, it caused a pricing paradox.": "价值如此强大，以至于引发了定价悖论。",
    "Are you an upgrade in disguise? Because you’re boosting my everything.": "你是伪装的升级版吗？因为你把我的一切都搞砸了。",
    "Buy now or regret eternally (and cosmically).": "现在就买，否则会后悔一辈子。",
    "Even my nightmares feature people missing this deal.": "就连我的噩梦里都有错过这笔交易的人。",
    "Granite Chunk": "花岗岩块",
    "Granite makes up most of Earth’s continental crust and can be over a billion years old.": "花岗岩构成了地球大陆地壳的大部分，其年龄可能超过10亿年。",
    "I can’t tell if that’s glow or legendary lighting.": "我分不清那是光还是传说中的光。",
    "My luck was flatlining until your entrance revived it.": "我的运气一直萎靡不振，直到你的到来才重新振作起来。",
    "That’s a face that’s seen every expansion and survived.": "这张脸见证了每一次扩张并幸存下来。",
    "These combos were forged in the fires of collector FOMO.": "这些组合是在收藏家FOMO的火焰中锻造出来的。",
    "Top pull to you, my glossy darling!": "上拉给你，我闪亮的宝贝！",
    "Trade in one glance, walk out with five dreams.": "交易一瞥，走出五个梦想。",
    "You won’t need luck with these offers. Multiple cards, multiple chances to ascend.": "获得这些机会不需要运气。多张卡片，多次提升机会。",
    "A better deal has never existed. And that’s a promise from a merchant.": "没有比这更好的交易了。这是一个商人的承诺。",
    "Ah, it’s you! The one whose junk pulls turn into gold.": "啊，是你！谁拉谁的垃圾，谁就变成金子。",
    "Ah, my favorite glittering customer!": "啊，我最喜欢的闪闪发光的顾客！",
    "Ahoy there! You shine brighter than my entire display shelf.": "喂! !你比我的整个展示架都亮。",
    "Ahoy, holographic hero! You make boosters look dull.": "啊哈，全息英雄！你让助推器看起来很沉闷。",
    "Ahoy, mint-condition miracle! Your skin glistens like freshly printed cards.": "嘿，崭新的奇迹！你的皮肤像刚印好的卡片一样闪闪发光。",
    "Be honest—did you get styled by exotic spirits?": "老实说，你是不是被异国情调的烈酒弄得晕头转向？",
    "Beaming brilliance, foil-fused greatness, and great hair? Classic you.": "灿烂的光辉，烫发的伟大，还有一头秀发？经典的你。",
    "Behold: value, sparkles, and a little mischief.": "瞧：价值，闪光，还有一点恶作剧。",
    "Behold! A collection king/queen has entered!": "看哪!一个集合国王/王后进场了！",
    "Black Hole pokes and Merchants can now give cards from Bugdom realm.": "黑洞点击和商人现在可以提供来自昆虫王国的卡片了。",
    "Bow down, junk piles! Royalty approaches.": "低头吧，垃圾堆！皇室的方法。",
    "Buy today and unlock a stack of fine-to-divine greatness. Bonus glimmer included.": "今天购买，解锁一堆精美到神圣的伟大。包括奖金微光。",
    "Card collectors rejoice: this is your dream spread.": "卡片收集者欢欣鼓舞：这是你梦想的传播。",
    "Cheers to you, sparkliest of collectors!": "为你干杯，最耀眼的收藏家！",
    "Decrease base cooldown for Sea World by 2s.": "减少海洋世界的基础冷却时间2s。",
    "Divine pull energy walks again!": "神拉能量再次行走！",
    "Don’t blink. The value might vanish from disbelief.": "不要眨眼。价值可能因为不相信而消失。",
    "Don’t call it a combo. Call it a lifestyle.": "不要称之为组合。称之为一种生活方式。",
    "Each of these offers has been infused with rare air and epic dust.": "每一个提议都被注入了罕见的空气和史诗般的尘埃。",
    "Even my most powerful bundle dimmed slightly in your glow.": "在你的光芒下，我最强大的力量也黯然失色。",
    "Even the junk cards here come with sparkle.": "即使是这里的垃圾卡片也闪闪发光。",
    "Even the junk pile straightened itself out for you.": "就连那堆垃圾也替你整理好了。",
    "Every card here rolled a natural 20 on fabulous.": "这里的每张卡片都打出了自然的20分。",
    "Generate stone equal to number of Realm 1 cards discovered squared per second.": "生成的石头等于每秒发现的领域1卡数的平方。",
    "Get these before the algorithm notices.": "在算法注意到之前把这些弄出来。",
    "Gleam on, holographic legend! You bring light to my shop.": "闪耀吧，全息传奇！你给我的店带来了光明。",
    "Greetings, deck sorcerer! Every exotic card here perked up at your scent.": "您好，甲板法师！这里的每一张异国卡片都被你的香味吸引住了。",
    "Greetings, hero of decks! Is that a decent card grin or are you just happy to see me?": "你好，牌组英雄！这是一个良好卡片笑容，还是你只是很高兴见到我？",
    "Greetings, my glossy friend! Your smile just boosted my rare card drop rate.": "问候，我光鲜的朋友！你的微笑提高了我的稀有卡片掉落率。",
    "Greetings, noble curator of all things shiny!": "尊敬的万物闪亮的馆长！",
    "Greetings, radiant champion! Your eyes sparkle brighter than a divine rarity pull.": "问候，容光焕发的冠军！你的眼睛比稀有的神器还要明亮。",
    "Hail, divinely dressed dealer! Your fashion is a fine rarity in itself.": "你好，衣着神圣的商人！你的时装本身就是一件极好的珍品。",
    "Hail, multi-card monarch! You make basic cards feel like rares.": "多卡片君主万岁！你让基本的卡片显得很稀有。",
    "Have I got a deal for you! A hand-picked stack of cards rarer than moonlight on mythic foil.": "我跟你做个交易！一堆精心挑选的卡片，比神话箔上的月光还要稀有。",
    "Hawking Radiation Harvester": "霍金辐射收割机",
    "Hello again! Your collection must glow in the dark from sheer excellence.": "你好了!你的收藏必须在黑暗中闪耀，因为它绝对是卓越的。",
    "Hello, collector supreme! Even my exotic cards feel humbled in your gaze.": "你好，至尊收藏家！在你的注视下，我的珍奇卡片也感到卑微。",
    "Hello, pack prodigy! I’d trade my finest exotic for your sense of style.": "你好，背包神童！我愿意用我最好的异国情调换你的时尚感。",
    "Hey there, card commander! Your mere presence shuffled my inventory.": "嘿，指挥官！你的出现打乱了我的清单。",
    "Hey, mythic magnet! Your skin glows like a divine first edition.": "嘿，神奇的磁铁！你的皮肤像神圣的初版。",
    "Hi again, epic embodiment! I bet your commons have backstories.": "你好，史诗化身！我敢打赌你的普通人都有背景故事。",
    "Hi there, shuffle sovereign! Your collection could start its own religion.": "你好，洗卡片君主！你的收藏可以形成自己的宗教信仰。",
    "Hi, noble pack whisperer! Even my junk cards tremble before your charisma.": "嗨，高贵的族群语者！在你的魅力面前，我的垃圾卡片都颤抖了。",
    "I can’t tell if that’s cologne or divine ink you’re wearing.": "我看不出你喷的是古龙水还是神墨。",
    "I had a divine once. You outshine it.": "我有一个神圣的曾经。你比它更耀眼。",
    "I heard you pulled three legendaries in one breath.": "我听说你一口气拉了三个传奇。",
    "I heard your collection made a foil cry once. Respect.": "我听说你的收藏曾经让一个陪衬哭过。尊重。",
    "I once offered this bundle to a god. They said, 'Too good.'": "我曾经把这个包裹献给一位神。他们说：“太好了。”",
    "I once thought I loved my collection—then I saw yours.": "我曾经以为我爱我的收藏——然后我看到了你的。",
    "I polished each of these personally—and they still sparkle less than your potential.": "我亲自打磨了每一件衣服，但它们仍然没有你的潜力那么耀眼。",
    "I sold a foil yesterday. It asked for you.": "我昨天卖了一个铝箔纸。它要找你。",
    "I sorted these with divine guidance. Or caffeine. Both work.": "我在神的指引下整理了这些。或咖啡因。这两个工作。",
    "I stacked these offers so high, they reached the divine archive.": "我把这些出价堆得很高，它们都到达了神圣的档案库。",
    "I swear your hair is trimmed with full-art borders.": "我发誓你的头发修剪得很漂亮。",
    "I tried pricing these bundles but they threatened to leave me.": "我试着给这些包裹定价，但他们威胁要离开我。",
    "If these cards had voices, they’d be singing love songs to you.": "如果这些卡片有声音，它们就会对你唱情歌了。",
    "If value had a shape, it would be this stack.": "如果价值有一个形状,这将是这个堆栈。",
    "Increase max offline time by 4 hours.": "最大离线时间增加4小时。",
    "It’s an honor to breathe the same rarified air as your deck.": "能和你的甲板呼吸同样的空气是我的荣幸。",
    "Junk? Basic? Pff. We’re skipping straight to the good stuff.": "垃圾吗?基本的?讨论。我们直接跳到精彩的部分。",
    "Just being near this bundle increases your win rate.": "只要靠近这个包就能提高你的胜率。",
    "Limited stock. Infinite style.": "有限的股票。无限的风格。",
    "Many seashell shapes follow the Fibonacci sequence in nature.": "自然界中许多贝壳的形状都遵循斐波那契数列。",
    "Multiple cards, zero regrets. Some even glow in the moonlight. Maybe.": "多张卡，零遗憾。有些甚至在月光下发光。也许吧。",
    "My display asked for a selfie with you.": "我的显示屏要求和你自拍。",
    "My mom said not to sell these. Good thing you're worth it.": "我妈说不要卖这些。好在你值得这么做。",
    "Negotiation Tactics": "谈判的策略",
    "No booster luck needed. Just smart picks—like these.": "不需要运气。就像这些聪明的选择。",
    "Oho! My best bundle whisperer returns!": "嗳哟!我最好的捆语者回来了！",
    "One click, 100% satisfaction rate.": "一次点击，100%满意率。",
    "Pick a pack, any pack! Each one handcrafted by imaginary elves and real excitement.": "挑一包，随便哪一包！每一个都是由想象中的精灵和真实的兴奋手工制作的。",
    "Pick three, get shocked by how perfect they are.": "选三个，为他们的完美而震惊。",
    "Praise be—you’re here to bless the bundles once more!": "赞美他——你又来为这捆礼物祝福了！",
    "Rarity? Overrated. These have soul. And okay, also rarity.": "罕见吗?被高估了。他们有灵魂。好的，还有稀有。",
    "Resource Generator": "资源发电机",
    "Rocks realm deselect cooldown multiplier reduced by 50%.": "岩石领域取消选择的冷却时间减少50%。",
    "Salutations! You shine like a freshly minted epic—flawless and powerful.": "你好!你像新铸造的史诗般闪耀——完美无瑕，充满力量。",
    "Seashell": "海贝",
    "Seaweed": "海藻",
    "Seaweed produces about 80% of Earth’s oxygen through photosynthesis.": "海藻通过光合作用产生大约80%的地球氧气。",
    "Starfish": "海星",
    "Starfish can regenerate lost arms—even grow a whole new body from one arm.": "海星可以再生失去的手臂，甚至可以从一只手臂长出一个全新的身体。",
    "The deals are limited. Your taste is not.": "这些交易是有限的。你的品味不是。",
    "The gods sent you to bankrupt my inventory, didn’t they?": "众神派你来让我破产，是吗？",
    "The shelves have been buzzing about your return.": "书架上都在议论你的归来。",
    "The shop literally shimmered when you walked in.": "当你走进来的时候，这家店真的闪闪发光。",
    "These cards are practically begging to be sleeved by you.": "这些卡片实际上是求你把它们收起来。",
    "These cards are so fresh, the print ink’s still emotionally attached.": "这些卡片太新鲜了，上面的墨水还很有感情。",
    "These cards? They tell stories. All heroic. All sparkly.": "这些卡片吗?他们讲故事。所有的英雄。所有闪闪发光。",
    "They say don’t meet your heroes. Unless they’re these cards.": "他们说不要见你心目中的英雄。除非是这些卡片。",
    "They say happiness can’t be bought. Clearly, they haven’t seen this bundle.": "他们说幸福是买不到的。很明显，他们还没有看到这个包。",
    "They say luck is random. Then you happened.": "他们说运气是随机的。然后你出现了。",
    "They say you can’t buy power. They didn’t see these prices.": "他们说权力是买不到的。他们没有看到这些价格。",
    "They sparkle. They shine. They want YOU.": "他们闪闪发光。闪闪发光。他们需要你。",
    "This deal? It’s basically a booster box in disguise.": "这笔交易吗?基本上就是一个伪装的助推器。",
    "This is what pulling a miracle looks like.": "这就是创造奇迹的样子。",
    "This merchant is not worthy—but these cards might be.": "这个商人不值得——但这些卡片可能值得。",
    "This offer includes cards, charm, AND mild emotional healing.": "这个服务包括卡片，魅力，和温和的情感治疗。",
    "This stack is spicy, shiny, and statistically superior.": "这一堆辣味十足，闪闪发光，而且在统计上更胜一筹。",
    "This stack is what other bundles aspire to be.": "这个堆栈是其他捆绑包所渴望的。",
    "This stack was born from a divine sneeze. Don’t ask.": "这个堆栈是由一个神圣的喷嚏产生的。不要问。",
    "Today only: a multi-pull deal hotter than a freshly sleeved exotic.": "只有今天：多拉交易比新袖的异国情调更热。",
    "Today’s menu: mystery, madness, and multi-card majesty.": "今天的菜单：神秘，疯狂，和多卡威严。",
    "Today’s special: deals that would make a mythic card question its self-worth.": "今天的特惠：将使神话卡质疑其自我价值的交易。",
    "Unbox a moment of pure joy. And then ten more.": "打开一个纯粹快乐的时刻。然后再来十次。",
    "Unleash your inner mythic with these bundles.": "用这些包裹释放你内心的神话。",
    "Unlock ability to offer merchant to buy all their cards for 5% discount.": "解锁能力，提供商人购买所有卡的5%折扣。",
    "Unlock Bugdom Realm": "解锁昆虫王国领域",
    "Unlock New Merchant": "解锁新商人",
    "Unlocks a device that can passively harvest Hawking radiation from the black hole to reduce its cooldown. (10x slower offline)": "解锁一个设备，可以被动地从黑洞中收集霍金辐射，以减少冷却时间。（脱机速度慢10倍）",
    "Want variety? These sets range from basic to divine, with a hint of chaos.": "想要不同吗?这些套装从基本的到神圣的，有一点混乱。",
    "Well butter my booster—it's you!": "好吧，黄油我的助推器-是你！",
    "Well hello! Your outfit today is sharper than any rare I’ve handled.": "嗯你好!你今天的衣服比我处理过的任何罕见的衣服都要锋利。",
    "Well met, binder deity! Your sleeves must be made of silk and destiny.": "很好，活页夹神！你的袖子必须用真丝和命运做成。",
    "What’s better than one epic card? How about five? Or ten? Take your pick!": "还有什么比一张史诗卡片更好的呢？5点怎么样？还是十?你自己选吧！",
    "Why stop at epic when divine is this affordable?": "既然神圣是可以承受的，为什么要止步于史诗？",
    "Yes, I’m throwing in extras. Because you’re fabulous.": "是的，我把额外的钱也算进去了。因为你太棒了。",
    "Yo ho! You arrive with the grace of a divine reveal.": "哟呵!你带着神圣启示的恩典来到这里。",
    "Yo yo! You radiate booster box energy like no other.": "溜溜球!你散发的能量是独一无二的。",
    "Yo! You look like someone who sleeps on a bed of legendarys.": "哟!你看起来就像睡在传奇之床上的人。",
    "You ever seen a combo so powerful it radiates? Now you have.": "你见过如此强大的连击吗？现在你有了。",
    "You're so radiant, even my RNG is nervous.": "你如此容光焕发，连我的RNG都紧张了。",
    "You’ve got taste, I’ve got stock—let’s make magic together.": "你有品位，我有库存，让我们一起创造奇迹。",
    "Your future deck is hiding in this pile.": "你未来的卡片就藏在这堆卡片里。",
    "Yvette Ambervale is added to pool of traveling merchants.": "伊薇特·安伯维尔加入了旅行商人池。",
    "A fine hello to the player whose basic cards are probably epic by now.": "这是一个很好的问候玩家，他们的基本卡牌现在可能是史诗级的。",
    "A toast to your magnificence and probable mythic hoard!": "为你的辉煌和可能的神话宝藏干杯！",
    "Act fast! These bundles are rarer than dragons in therapy.": "行动快!这些包裹在治疗中比龙还罕见。",
    "Ahoy, exotic entity! My humble wares barely match your sparkle.": "你好，异域生物！我简陋的衣服根本配不上你的光彩。",
    "Ancient footwear found in rivers helps archaeologists date human settlements.": "在河流中发现的古鞋可以帮助考古学家确定人类居住的年代。",
    "Deck optimization? Starts right here, friend.": "甲板优化?从这里开始，朋友。",
    "Driftwood": "浮木",
    "Driftwood can float for years, carried across entire oceans.": "浮木可以漂浮数年，穿越整个海洋。",
    "Greetings! My mythics blushed when you walked in.": "问候!当你走进来时，我的神话羞红了脸。",
    "Hail, mighty trader! Even my divine cards whisper about your beauty.": "你好，伟大的商人！连我神圣的卡片都在低语你的美丽。",
    "I've never been so proud to sell anything.": "我从来没有为卖东西这么自豪过。",
    "Jellyfish": "水母",
    "Junk? Not here. Just joy, charm, and cardboard glory.": "垃圾吗?不在这里。只有欢乐、魅力和纸板上的荣耀。",
    "My ancestors would haunt me if they knew how cheap these were.": "如果我的祖先知道这些东西有多便宜，他们会缠着我的。",
    "My eyes! They’re blinded by your binder's brightness.": "我的眼睛!他们被你活页夹的亮度蒙蔽了双眼。",
    "Oh yes, the binder oracle returns once again!": "对了，活页神谕又回来了！",
    "Old Boot": "旧的引导",
    "Pick any pile—each one’s been blessed by the RNG gods and spritzed with exotic magic.": "随便挑一堆，每一堆都被RNG的神保佑，并被喷上了奇异的魔法。",
    "Some jellyfish species are biologically immortal, reverting to juvenile form to avoid death.": "有些水母在生物学上是不朽的，它们会恢复到幼年状态以避免死亡。",
    "These cards aren’t random. They chose you.": "这些卡片不是随机的。他们选择了你。",
    "Want a binder that glows in the dark? Start with these picks.": "想要一个在黑暗中发光的活页夹吗？从这些选择开始。",
    "Welcome to the buffet of brilliance—pick your platter.": "欢迎来到辉煌的自助餐，挑选你的拼盘。",
    "Whoa! Did the RNG gods send you or what?": "哇!是RNG的神派你来的吗？",
    "Yo! Even my exotic cards bowed when you walked in.": "哟!当你走进来的时候，连我的异域风情卡片都鞠躬了。",
    "You deserve a deck that intimidates your reflection. Let’s start here.": "你应该有一副能吓到自己的牌。让我们从这里开始。",
    "You deserve cards that match your radiance. These will do.": "你应该得到与你的光芒相匹配的卡片。这些就行了。",
    "You look like someone who knows a good foil when they see one.": "你看起来就像知道什么是好的陪衬纸的人。",
    "You’re not buying cards, you’re investing in glory. Multiple times over.": "你不是在买卡牌，你是在投资荣誉。好几次了。",
    "Ah yes, the living embodiment of a full exotic set!": "啊，对了，这是异域风情的化身！",
    "Buy now, and I’ll throw in a wink and my eternal merchant loyalty.": "现在买，我就给你一个眼色和我永远的商人忠诚度。",
    "Each card in this pile has a secret. And you’ll love every one.": "这堆牌中的每张牌都有一个秘密。你会爱上每一个人。",
    "Greetings, deck demigod! You radiate the smell of sealed product.": "你好，甲板上的半神！你散发着密封产品的气味。",
    "I tuned this bundle for a deck only you could build.": "我调整了这个包，让它成为一个只有你才能打造的桥牌。",
    "I’d offer you my best, but you ARE my best customer.": "我会给你最好的，但你是我最好的客户。",
    "Is it hot in here, or did you bring mythic heat?": "这里真的很热吗，还是你带来了传说中的热？",
    "Legends say whoever owns this bundle becomes 17% more charming.": "传说，谁拥有这个包，谁的魅力就会增加17%。",
    "My inventory just cheered in your honor.": "我的存货清单为你喝彩。",
    "No time for booster roulette—my bundles deliver straight euphoria.": "没时间玩助推器轮盘赌了，我的包裹会带来直接的快感。",
    "Quantity meets quality. And then they high-fived.": "数量满足质量。然后他们击掌。",
    "This bundle was crafted by goblin economists. It’s flawless.": "这种捆绑是由妖精经济学家精心设计的。它是完美的。",
    "Harvester": "收割机",
    "Harvester Upgrade": "收割机升级",
    "Fleeting Realm": "飞逝之境",
    "Forsaken Realm": "遗忘之境",
    "Ant": "蚂蚁",
    "Beetle": "甲虫",
    "Butterfly": "蝴蝶",
    "/ Sec Multiplier:": "/ 秒 乘数:",
    "Buyout Cost:": "买断成本:",
    "DECENT": "良好",
    "Global": "全局",
    "Seahorse": "海马",
    "To Hell with Bugs": "让虫子见鬼去吧",
    "A dazzling day to you, slayer of junk pulls!": "祝你有一个令人眼花缭乱的一天，垃圾杀手拉！",
    "A shimmer in the air… must be you approaching.": "空中有闪光，一定是你在靠近。",
    "A wild beauty appears—and they smell like fresh pulls.": "一种野性的美出现了——它们闻起来像新鲜的拉花。",
    "Absorber Upgrade": "吸收器升级",
    "Ah yes, the one whose touch upgrades rarity.": "啊，是的，那个触摸就能升级稀有的人。",
    "Ahoy, unmatched icon! Your binder probably levitates.": "哇，无与伦比的图标！你的活页夹可能会悬浮起来。",
    "Ants can lift objects over 50 times their body weight.": "蚂蚁能举起超过其体重50倍的物体。",
    "Are those exotic eyes I see? Magnificent.": "我看到的是异域风情的眼睛吗？宏伟的。",
    "Are you sure you’re not secretly a divine avatar?": "你确定你不是神的化身吗？",
    "Auto-User Absorber": "自动使用者吸收器",
    "Beetles make up about 40% of all known insect species.": "甲虫约占所有已知昆虫种类的40%。",
    "Behold, the one who once pulled divine back-to-back!": "瞧，那个曾经把神拉到背靠背上的人！",
    "Black Hole pokes and Merchants can now give cards from Aviary realm.": "黑洞点击和商人现在可以从鸟舍王国赠送卡片了。",
    "Blessed are we to witness such collection majesty.": "我们有幸目睹如此壮观的收藏。",
    "Blessings upon the most dashing card slinger alive!": "祝福最潇洒的牌手！",
    "Bugdom realm deselect cooldown multiplier reduced by 50%.": "昆虫王国取消选择的冷却时间减少50%。",
    "Bundle bonus! Every third card might whisper secrets of the divine.": "卡包奖励!每三张卡上都有神的秘密。",
    "Butterflies taste with their feet to find host plants.": "蝴蝶用脚品尝来寻找寄主植物。",
    "Cards don’t get jealous—unless you walk by.": "卡片不会被嫉妒——除非你路过。",
    "Caterpillar": "毛毛虫",
    "Caterpillars can increase their body mass up to 100 times before metamorphosis.": "毛毛虫在变形前体重可增加100倍。",
    "Coral Fragment": "珊瑚碎片",
    "Coral reefs support 25% of all marine species while covering less than 1% of the ocean.": "珊瑚礁支撑着25%的海洋物种，而覆盖的海洋面积不到1%。",
    "Creepy Crawlies Creep Me Out": "令人毛骨悚然的小爬虫让我毛骨悚然",
    "Decent Cards Are Beneath Me": "良好卡片是我的身份",
    "Decrease base cooldown for Bugdom by 5s.": "减少昆虫王国的基础冷却时间5秒。",
    "Don’t settle for a single card—grab a full spectrum of rarities while they last!": "不要满足于一张卡片——在它们还在的时候抓住所有的稀有卡片！",
    "Dusty Artifacts, Ugh": "满是灰尘的文物",
    "Each card’s been pre-approved by fate and fashion.": "每张卡片都是命运和时尚预先批准的。",
    "Even divine packs would queue for your autograph.": "就连神包也会排队要你的签名。",
    "Even my rivals would cry if they saw me selling these this cheap.": "如果我的竞争对手看到我卖这么便宜，他们也会哭的。",
    "Even the divine deck upstairs wants this pile.": "就连楼上的神甲板都想要这一堆。",
    "Even the sleeves are trembling with anticipation.": "连袖子都在期待中颤抖。",
    "Every pile comes with a sprinkle of enchantment and a dash of absurd value.": "每一堆都带有一点迷人和一点荒谬的价值。",
    "Everything here is legal in tournaments... mostly.": "这里的一切在锦标赛中都是合法的……主要是。",
    "Everything must go—but only to legends like you.": "一切都必须离开，但只留给像你这样的传奇人物。",
    "Foil sparkles in your eyes, and charm in your aura.": "你的眼睛闪闪发光，你的气场充满魅力。",
    "Gasp! Your presence just bent the rarity scale.": "喘息!你的出现改变了稀有度。",
    "Generate coral equal to number of Realm 2 cards discovered squared per second.": "生成珊瑚等于每秒发现的领域2卡数的平方。",
    "Good morrow, card baron! My shop feels upgraded just by your presence.": "明天好，卡男爵！你的到来让我的店焕然一新。",
    "Gotta Catch 'Em All": "要把他们都抓起来",
    "Grasshopper": "蚱蜢",
    "Gravitational Wave Absorber": "引力波吸收器",
    "Great pulls and even greater cheekbones? Unfair advantage!": "拉得更大，颧骨更大？不公平的优势!",
    "Greatness isn’t born. It’s bought—right here.": "伟大不是天生的。就在这里买的。",
    "Greetings, radiant one! Your very being is more polished than my divine set.": "你好，容光焕发的人！你的存在比我的神圣的套装更优雅。",
    "Greetings, stack-slayer! My rares are starstruck by your collection.": "你好，堆叠杀手！我的宝贝们被你的收藏迷住了。",
    "Hark! A mythic aura surrounds you, friend.": "听!朋友，你周围有一种神秘的气氛。",
    "Hello again, vault-worthy visitor! My epic cards want your autograph.": "你好，有价值的访客！我的史诗卡片想要你的签名。",
    "Hello hello! You shimmer like a freshly pulled exotic.": "你好你好!你就像刚拉出来的异域风情。",
    "Hello, chosen one! The divine card realm speaks highly of your luck.": "你好，天之骄子！神牌界对你的运气评价很高。",
    "Hello, connoisseur of cardboard! You radiate deck synergy!": "你好，纸板鉴赏家！你辐射甲板协同！",
    "Hey hero! Your binder walks so other binders can run.": "嘿,英雄!你的活页夹走了，其他活页夹就可以跑了。",
    "Hey hey! You sparkle like a card fresh from a triple-sealed pack.": "嘿嘿!你就像刚从三层密封盒里出来的卡片一样闪闪发光。",
    "Hey there, style incarnate! Your rares envy you.": "嘿，时尚的化身！你的亲人羡慕你。",
    "Hey there! Your aura is more legendary than anything I’ve ever sleeved.": "嘿!你的光环比我戴过的任何东西都更具传奇色彩。",
    "Hey you! Were you sculpted by booster gods?": "嘿,你!你是由助推器之神雕刻的吗？",
    "Heyo, cardboard champion! You radiate balance and binder bulk.": "嘿，纸板冠军！你散发出平衡和活力。",
    "Hi hi! Has anyone ever told you that your posture screams binder alpha?": "嗨嗨!有没有人告诉过你，你的姿势很像活页夹？",
    "Hi there, foil-souled legend! The cards practically stood up when you entered.": "嗨，有箔灵魂的传奇！你进去的时候，卡片几乎都竖起来了。",
    "Hi! You glow like someone who’s seen every foil twice.": "嗨！你就像看过两次箔纸的人一样容光焕发。",
    "How many cards? Enough to make your rivals weep.": "有多少张牌？足以让你的对手哭泣。",
    "Huzzah! My luck increased tenfold just from your hello.": "万岁!你的问候使我的运气增加了十倍。",
    "I Ain't No Basic Bitch": "我不是基本的婊子",
    "I enchanted them myself. With value.": "我自己给他们施了魔法。与价值。",
    "I laid out these cards like constellations. Find your destiny.": "我把这些卡片像星座一样排列。找到你的命运。",
    "I made a deal with the RNG spirits to get these into your hands.": "我和RNG的灵魂达成协议把这些交给你。",
    "I mixed luck, style, and cardboard. This bundle was born.": "我把运气、风格和硬纸板混合在一起。这个包就这样诞生了。",
    "I once saw a mythic cry when you ignored it.": "我曾经看到过一个神话般的哭泣，当你无视它时。",
    "I tried to prepare, but nothing outshines your aura.": "我试过准备，但没有什么能比你的光环更耀眼。",
    "I was just telling my junk pile about you!": "我只是在跟我那堆垃圾说你的事！",
    "I’d trade my whole shelf just to watch you organize cards.": "为了看你整理卡片，我愿意换掉我的整个书架。",
    "I'm Sick of you Maribel": "我受够你了，玛丽贝尔",
    "If cardboard envy was a stat, I’d be maxed out.": "如果“纸板嫉妒”是一种统计，我早就顶不住了。",
    "If majestic had a face, it’d look exactly like yours.": "如果磅礴有张脸，肯定和你一模一样。",
    "If you pulled any more charm, the server would crash.": "如果你再施展魅力，服务器就会崩溃。",
    "Imagine pulling your next favorite. Now make it reality.": "想象一下拉出你的下一个最爱。现在让它成为现实。",
    "Increase Merchant Rarity Scaling by 0.1.": "增加商人稀有度比例0.1",
    "Increases max cards per poke by 40.4.": "每点击增加最大卡数40.4。",
    "Increases min cards per poke by 4.04.": "增加每点击最少卡数4.04。",
    "Interceptor Upgrade": "拦截器升级",
    "It’s not magic. It’s markdowns.": "这不是魔法。这是降价促销。",
    "It’s the gorgeous goblin-smasher with flawless pulls!": "这是一款完美无瑕的地精粉碎器！",
    "It's YOU! My sleeves just sorted themselves.": "这是你!我的袖子自己整理好了。",
    "Knights wish they looked this rare.": "骑士们希望它们看起来这么稀有。",
    "Let’s build your binder the way fate intended: in bulk.": "让我们按照命运的安排来建造你的活页夹：散装的。",
    "Male seahorses carry and give birth to their young.": "雄性海马会带孩子，也会生孩子。",
    "Marble is metamorphosed limestone and was used by Michelangelo to carve David.": "大理石是变质的石灰石，米开朗基罗用它来雕刻大卫。",
    "Marble Slab": "大理石板",
    "Marine Life Makes Me Queasy": "海洋生物让我恶心",
    "My finest table. For my finest customer.": "我最好的桌子。给我最好的顾客。",
    "My junk pile’s prettier than some people’s epic shelves.": "我的破烂堆比别人的书架还漂亮。",
    "My shop’s never looked better than with you inside.": "有你在，我的店最漂亮了。",
    "Negotiation Tactics 2": "谈判策略2",
    "Negotiation Tactics 4": "谈判策略四",
    "Not sold in stores. Or realms. Or dimensions.": "商店里不卖。或领域。或维度。",
    "Oh my stars—it’s the one who sleeved destiny itself!": "哦，我的星星——是他把命运套上了袖子！",
    "One small purchase for you, one giant leap for your binder.": "你买了一件小钱，你的活页夹就有了一大步。",
    "Only a fool would walk away. And you’re no fool.": "只有傻瓜才会走开。你也不傻。",
    "Only for you: a bundle so legendary it filed its own lore entry.": "专为你准备的：一束如此传奇的东西，它已经有了自己的爱情记录。",
    "Orin Saltstride is added to pool of traveling merchants.": "奥林盐田被添加到旅行商人池。",
    "Over 3 million shipwrecks lie on the ocean floor, preserving maritime history.": "超过300万艘沉船躺在海底，保存着海洋历史。",
    "Pick a card. Any card. Or better yet—pick them all.": "选一张牌。任何卡。或者更好的是，把它们都挑出来。",
    "Pick any three cards from this table—each one more majestic than the last.": "从这张桌子上随便挑三张牌，一张比一张气派。",
    "Poke. Smile. Repeat.": "戳。微笑。重复。",
    "Praise the RNG, it’s you!": "赞美RNG，是你！",
    "Rarely Impressed": "很少的印象",
    "Realm Conqueror": "领域征服者",
    "Rejoice! The most radiant pack opener has returned!": "喜乐!最闪亮的开包器回来了！",
    "Rumor says your collection caused three vendors to faint.": "有传言说你的藏品让三个小贩晕倒了。",
    "Rumors say your binder formed its own religion.": "有传言说你的活页夹形成了自己的宗教。",
    "Salutations, holo-hearted beauty! Did you foil your hair today?": "敬礼，虔诚的美人！你今天烫头发了吗？",
    "Salutations, sparkly one! You smell like holographic victory.": "致敬，闪亮的人！你闻起来像全息胜利。",
    "Salutations! My sleeves just straightened themselves in your presence.": "你好!我的袖子刚在你面前伸直了。",
    "Sea World realm deselect cooldown multiplier reduced by 50%.": "海洋世界领域取消选择的冷却时间减少50%。",
    "Shipwreck": "海难",
    "Shut up Cedric": "闭嘴，塞德里克",
    "So shiny! My holo cards look matte next to you.": "所以闪亮!我的贺卡在你面前很难看。",
    "Some grasshoppers can jump over 20 times their body length.": "一些蚱蜢可以跳超过其体长20倍的距离。",
    "Special offer! One junk, one mythic, and three cards that defy classification.": "特别优惠!一张垃圾牌，一张神话牌，还有三张无法分类的牌。",
    "Sweet rolls! Your shine rivals my best holo!": "甜蜜的滚!你的光芒与我最耀眼的光环相媲美！",
    "Take three, get an ego boost free.": "吃三片，免费提升自我。",
    "That feeling of a perfect pull? Times it by five.": "那种完美拉动的感觉？乘以5。",
    "The gods blinked twice when I priced this one.": "当我给这个定价时，诸神眨了两次眼。",
    "The light bends around you like a perfectly graded 10.": "光线在你周围弯曲，就像一个完美的10分。",
    "The Sea Scares Me": "大海让我害怕",
    "The way you walk? That’s holographic energy.": "你走路的样子？这就是全息能量。",
    "These aren't just cards. They’re destiny accelerators.": "这些不仅仅是卡片。它们是命运加速器。",
    "These cards are smarter than me, and I’m the one selling them.": "这些卡片比我聪明，是我在卖它们。",
    "These stacks are rare. Like your taste. Well played.": "这种堆叠很罕见。喜欢你的口味。好打。",
    "These stacks? Stacked with greatness. Literally.": "这些栈?充满了伟大。字面上。",
    "They say gods created divine cards... then you outshined them.": "他们说上帝创造了神圣的卡片……然后你就比他们更耀眼了。",
    "They say too many cards spoil the deck. I say... blasphemy!": "他们说太多牌会毁了一副牌。我说…亵渎!",
    "This bundle has been personally shuffled by destiny.": "这一捆已经被命运亲自洗牌了。",
    "This deal is to die for—figuratively. Probably.": "这是一笔梦寐以求的交易。可能。",
    "This deal was foretold. And now, it's yours to claim.": "这笔交易早有预兆。现在，轮到你了。",
    "This isn’t a sale. This is a once-per-lifetime convergence.": "这不是打折。这是一次生命周期的收敛。",
    "This merchant bows to greatness made manifest.": "这位商人向显扬的伟大鞠躬。",
    "This stack? A certified rainbow of cardboard destiny.": "这个栈?命运纸板制成的彩虹。",
    "Three cards per hand? Why not grab six?": "每手三张牌？为什么不去吃六块呢？",
    "Top of the draw pile to you! Your vibe says foil collector, your eyes say mythic menace.": "抽到第一名给你！你的感觉像是锡箔收藏家，你的眼神像是神秘的威胁。",
    "Unlock Aviary Realm": "解锁鸟舍领域",
    "Unlock Celestial Bodies Realm": "解锁天体领域",
    "Unlock Greek Gods Realm": "解锁希腊诸神王国",
    "Unlock Mythical Beasts Realm": "解锁神秘野兽王国",
    "Unlocks a device that absorbs gravitational waves each time black hole is poked. Can be activated to multiply card count for next poke. (Max 5x)": "打开一个装置，每次黑洞被戳时都会吸收引力波。可以激活的倍增卡计数为下一个戳。(最大5 x)",
    "Warm welcomes to the glowiest soul this shop has seen.": "热烈欢迎这家店见过的最耀眼的灵魂。",
    "Warning: Side effects of today’s bundles include excessive smugness.": "警告：今天的捆绑包的副作用包括过度沾沾自喜。",
    "Welcome back, divine rarity with legs!": "欢迎回来，有腿的稀有神兽！",
    "Welcome to the sale of the century. Possibly the millennium.": "欢迎来到世纪大拍卖。可能是千禧年。",
    "Well met, archive overlord! Even your shadow radiates binder prestige.": "幸会，档案领主！就连你的影子也散发着粘合剂的威望。",
    "Well met! Your aura makes junk cards re-evaluate their life.": "好满足!你的光环让垃圾卡重新评估他们的生活。",
    "Well met! Your card binder must weigh as much as a dragon's hoard.": "好满足!你的卡片夹必须和龙的宝藏一样重。",
    "Well now! My commons just hid behind the shelf.": "现在!我的同伴就躲在架子后面。",
    "Who Cares About Old Crap": "谁在乎旧垃圾",
    "Why choose one card when you can choose *power*?": "当你可以选择“能量”时，为什么要选择一张卡？",
    "You don’t need a pull today—you ARE the pull.": "今天你不需要别人来拉你，你就是那个人。",
    "You like drama? These cards have *lore.* All of them. Even the junk ones.": "你喜欢戏剧？这些卡片有爱。所有的。即使是垃圾垃圾。",
    "You like options? I’ve got a spread that’d make a divine collector blush.": "你喜欢选择吗？我有一幅能让神圣的收藏家脸红的画。",
    "You must be made of mythics—you light up the room!": "你一定是由神话组成的——你照亮了整个房间！",
    "You pull these, you win style points. Guaranteed.": "拉上这些，你就能赢得造型分。保证。",
    "You pull, I cheer. We call that the ritual of the lucky.": "你拉，我欢呼。我们称之为幸运的仪式。",
    "You smell like a perfectly sleeved destiny.": "你闻起来像个完美的命运女神。",
    "You smell like ink, destiny, and one-of-a-kind glory.": "你闻起来像墨水，命运和独一无二的荣耀。",
    "You sparkle harder than my most sleeved rare.": "你比我最漂亮的衣服还闪耀。",
    "You won’t need sleeves—these cards hug your soul.": "你不需要袖子——这些卡片拥抱你的灵魂。",
    "You're back! Even my divine cards want your attention.": "你回来!连我的神牌都想让你注意。",
    "You're here! The rares began whispering sweet nothings.": "你在这里!稀有动物开始低声说些甜言蜜语。",
    "You’re rarer than a card with working centering.": "你比有工作中心的卡片还稀有。",
    "/ Poke Multiplier:": "/ 点击 乘数:",
    "Blue Jay": "蓝松鸦",
    "Blue Jays mimic the calls of hawks to scare away other birds.": "蓝松鸦模仿老鹰的叫声来吓跑其他鸟类。",
    "Crow": "乌鸦",
    "Crows remember human faces and can hold grudges for years.": "乌鸦能记住人的脸，而且能记仇多年。",
    "Goldfinch": "金翅雀",
    "Goldfinches are strict vegetarians, unlike most other birds.": "与大多数其他鸟类不同，金翅雀是严格的素食者。",
    "Pigeon": "鸽子",
    "Sparrow": "麻雀",
    "Sparrows can swim short distances by flapping their wings and hopping across the water.": "麻雀可以通过拍打翅膀和跳水游很短的距离。",
    "Pigeons can recognize themselves in mirrors—one of the few species with this ability.": "鸽子能在镜子中认出自己——是少数具有这种能力的物种之一。",
    "Robin": "知更鸟",
    "Robins can hear worms moving underground using their keen sense of hearing.": "知更鸟可以用敏锐的听觉听到虫子在地下移动。",
    "A fancy lady. She does not carry junk.": "一个漂亮的女人。她不带垃圾。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Yvette Ambervale": "伊薇特·安博维尔",
    "Cedric Stormforge": "塞德里克·风暴熔炉",
    "Maribel Tealeaf": "玛丽贝尔·蒂叶",
    "Aldric Farwander": "Aldric Farwander",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Reset all currencies to ": "将所有货币重置为 ",
    "Lvl: ": "等级: ",
    "Tier: ": "层级: ",
    "Qty: ": "数量: ",
    "Time Offline: ": "离线时间: ",
    "(Unlocks at level ": "(解锁于等级 ",
    "Max Lvl ": "最大等级 ",
    "Unlock New Merchant ": "解锁新商人 ",
    "Absorber Upgrade ": "吸收器升级 ",
    "Resource Generator ": "资源生成器 ",
    "Faster Poke ": "更快的点击 ",
    "Faster Merchant ": "更快的商人 ",
    "Fan of Capitalism ": "资本主义的粉丝 ",
    "Get Unstuck ": "摆脱困境 ",
    "Lucky Skip ": "幸运跳跃 ",
    "Massive Black Hole ": "巨大的黑洞 ",
    "More Cards ": "更多卡片 ",
    "Not Less Cards ": "不减少卡片 ",
    "Harvester Upgrade ": "收割机升级 ",
    "Fleeting Realm ": "飞逝之境 ",
    "Forsaken Realm ": "遗忘之境 ",
    "Even Faster Poke": "超快的点击",
    "Card Supernova": "卡片超新星",
    "Casual Gamer": "休闲玩家",
    "Anomaly": "异常",
    "Better Merchants": "更好的商人",
    "Resourceful Pokes": "多面手",
    "Shorter Sacrifice": "更短的牺牲",
    "Larger Card Stacks": "更大的卡组",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "% chance to skip Black Hole cooldown.": "% 几率以跳过黑洞冷却时间.",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\-([\d\.]+)K$/,
    /^\-([\d\.]+)M$/,
    /^\+([\d\.]+)K$/,
    /^\+([\d\.]+)M$/,
    /^\+([\d\.]+)s$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^\+([\d\.]+) \| ([\d\.]+)$/,
    /^\+([\d\.]+) \| ([\d\.]+)K$/,
    /^([\d\.]+) \| ([\d\.]+)$/,
    /^([\d\.]+) \| ([\d\.]+)K$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\)$/,
    /^T([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^\(base: (.+) lvl × (.+) tier\)$/, '(基础: $1 等级 × $2 层级)'],
    [/^\((.+) base: (.+) lvl × (.+) tier\)$/, '($1 基础: $2 等级 × $3 层级)'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+)m([\d\.,]+)s$/, '$1分$2秒'],
    [/^\+([\d\.,]+) to max cards per poke.$/, '\+$1 每次点击获得的卡片上限。'],
    [/^\+([\d\.,]+) to min cards per poke.$/, '\+$1 每次点击获得的卡片下限。'],
    [/^\+([\d\.,]+) card offered by merchants.$/, '\+$1 商人提供的卡片。'],
    [/^Rare Income ([\d\.,]+)$/, '稀有收入 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Next Tier at Qty ([\d\.,]+)$/, '到下一层级需要数量 $1'],
    [/^Leaves in ([\d\.,]+)s$/, '$1秒后离开'],
    [/^Leaves in ([\d\.,]+)m([\d\.,]+)s$/, '$1分$2秒后离开'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) for Tier ([\d\.,]+)$/, '$1 到层级 $2'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);